### PR TITLE
Added compatible software badges

### PR DESCRIPTION
**Pull request by Legion2**
Added iCUE badge
Added RGBSync badge @Fanman03 
Added OpenRGB badge @CalcProgrammer1

### CODE REVIEW

**Comment by CalcProgrammer1** [comment]
I can whip up an "OpenRGB Compatible" badge with a black background to match the others sometime soon.  I like the idea!

**Comment by Legion2** [comment]
@CalcProgrammer1 you can open a PR or write here if your "OpenRGB Compatible" badge is ready.

**Comment by CalcProgrammer1** [comment]
I've created the badge.  I rendered it very large so you can downscale it and have it still look good.

OpenRGB Compatible

**Comment by Legion2** [comment]
updated

**Pull request merged**
