### PR TITLE
Create HoodLoader2CLPUnoMegaController_NonAddressable

### PR DESCRIPTION
**Pull request by jaki-gh**
Use this instead of the HoodLoader2CLPUnoMegaController if you want to use non-addressable LEDs with your Arduino Uno.

### CODE REVIEW

**Comment by jaki-gh** [comment]
This might work with the Arduino Mega but I haven’t tested it.

**Comment by Legion2** [comment]
Instead of defining two channels, the second led of the first channel can be used to get the color for the non addressable Led.

**Comment by jaki-gh** [comment]
Great idea! Let me fix that up!

**Comment by jaki-gh** [comment]
Should be fixed but I haven't tested it yet

**Comment by jaki-gh** [comment]
Unfortunately, I could not get it to work on one channel. I am a beginner and it took a very long time just to get this to work. The only one that works is in the /dev branch.

**Comment by jaki-gh** [comment]
Fixed patch 1! It is ready to merge! It still uses two channels. I couldn't figure out what I was doing wrong.

**Pull request closed without merging**
