### PR TITLE
Version 0.15.0

### PR DESCRIPTION
**Pull request by Legion2**
- add support for TinyUSB (Adafruits SAMD Boards, Raspberry Pi Pico, ESP32, [see all](https://github.com/adafruit/Adafruit_TinyUSB_Arduino#supported-cores)) thanks to @Spegs21 #215
- fix a timer overflow which happens if the arduino runs for many months #204
- updated documentation

Breaking Changes
- `CorsairLightingFirmware` have now a constructor with two arguments, the first is the corsair product type and the second is a storage interface for the firmware
- The `FastLEDController` persistence is now configured with a `FastLEDControllerStorage` object instead of a boolean in the constructor
- The type of the device id changed from `byte[]` to `DeviceID`

All examples has been updated with this changes.

### CODE REVIEW

**Comment by Legion2** [comment]
@Spegs21 should we fix #246 before we release this?

**Comment by Spegs21** [comment]
> @Spegs21 should we fix #246 before we release this?

@Legion2 I'm trying to figure out if this is limited to the Pico but I can't get fastled to work on my Trinket M0, Fastled/Fastled#1363. If it is based on the Pico then I think we can go ahead with the release as it's probably an issue with the Pico core.

**Comment by cnn123666** [comment]
@Spegs21 Is Pico the only one with this problem?

**Comment by Spegs21** [comment]
@Legion2 I think I should update the documentation to advise the use of a level shifter or buffer with the TinyUSB boards at 3.3v IO levels. @cnn123666 has shown it can work but it technically out of spec for the WS2812B.

**Comment by cnn123666** [comment]
@Spegs21 I seem to understand what is going on. Do I need to connect a level converter or buffer to Pico and then ws2812?

**Comment by Spegs21** [comment]
> @Spegs21 I seem to understand what is going on. Do I need to connect a level converter or buffer to Pico and then ws2812?

@cnn123666 In an ideal environment you would need one. Logic high level for the WS2812B is 0.7xVcc. That means at 5v VCC on the WS2812B it needs 3.5v to register a high logic level. The Pico IO is 3.3v, so it technically can't drive logic high on the WS2812B but you can get away with it if tolerances were lax enough in some cases.

A 1G126 buffer is prefect for this application. I can confirm it works well with the WS2812B leds.

**Comment by cnn123666** [comment]
@Spegs21 Thanks, I expect to test Pico + SN74AHCT1G126 within this week, but why is the frame rate normal after closing ICUE

**Comment by Spegs21** [comment]
@cnn123666 We don't know yet. It's not because of the lack of buffer though. It's not related.

**Comment by cnn123666** [comment]
I would like to buy other development boards to test TinyUSB, is there anything worth recommending

**Comment by Spegs21** [comment]
@cnn123666 74hc245c is not a good option because it still expects 0.7xVcc min input for logic high. VCC of the buffer has to be 5v. It won't be any better than not using a buffer.
The chip I'm using has lowered input logic high threshold to 2v regardless of VCC.

**Comment by Spegs21** [comment]
@Legion2 I finally got it working with the Trinket M0. I had to force software pins in FastLED. I've run the fan through a few different animations and I can confirm it appears to be functioning at full speed.

**Comment by Legion2** [comment]
So there close #246 and release this?

**Comment by Spegs21** [comment]
@Legion2 The issue with pico still exists. The Trinket M0 is a SAMD21. We can close the Pi Pico support issue and open a new one for slow animations if you want to go ahead with the release.

**Pull request merged**
